# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c179885216d5a413cd18a59c3cda5ca3f3d5de3034f0f30ddba0a9e4c301543c6ff48c0ea6b8e0f08612b6ac7fe84e6e05fd973f61dd365a5c100a609147a5a

test:
  secret_key_base: 75efe43375b9d378c91d786aa5f30e966c35657f58f59fe13ec99050ab4a13183a385e3044942228cdeca746dde7a9144e909769f4a578102de5d4231e6bf55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
